### ISSUE TITLE
Transfer halts if all the files from the changelist have been obliterated

### ISSUE THREAD

**Issue by fhautekeete** [perforce/p4transfer#4]
Windows 10
Python 2.7

Some of the folders in our depot have been obliterated. "P4 submit" yields an error as listed below. P4Transfer should skip the 'empty' changelist and continue.

-------------------------------------------------------
log tail:

2021-02-28 23:00:44,178:P4Transfer:ERROR: [P4#run] Errors during command execution( "p4 submit -i" )

	[Error]: 'No files to submit.'

Traceback (most recent call last):
  File "P4Transfer.py", line 1817, in replicate
    num_changes = self.replicate_changes()
  File "P4Transfer.py", line 1671, in replicate_changes
    targetChange = self.target.replicateChange(filerevs, change, self.source.p4.port)
  File "P4Transfer.py", line 1044, in replicateChange
    raise e
P4Exception: [P4#run] Errors during command execution( "p4 submit -i" )

	[Error]: 'No files to submit.'

**Comment by rcowham** [comment]
Interesting point. Possibly related - a queston about +Sn revisions. Will have a look.

**Comment by rcowham** [comment]
Hi @fhautekeete - can you include an excerpt of log file around the obliterated changes. Feel free to santize filenames and paths etc.

**Comment by rcowham** [comment]
Thanks for update. There have been changes to revert all currently opened files - which would resolve this particular problem.
I tested obliterates and if all files are obliterated, then the changelist would not show up anyway as one to be transferred!
